export = {
  'behaviour.analysis': require('./behaviour.analysis/') as typeof import('./behaviour.analysis/'),
  'edge.polyline': require('./edge.polyline') as typeof import('./edge.polyline'),
  'edge.quadraticCurve': require('./edge.quadraticCurve/') as typeof import('./edge.quadraticCurve/'),
  'layout.archimeddeanSpiral': require('./layout.archimeddeanSpiral/') as typeof import('./layout.archimeddeanSpiral/'),
  'layout.circle': require('./layout.circle/') as typeof import('./layout.circle/'),
  'layout.dagre': require('./layout.dagre/') as typeof import('./layout.dagre/'),
  'layout.forceAtlas2': require('./layout.forceAtlas2/') as typeof import('./layout.forceAtlas2/'),
  'layout.grid': require('./layout.grid/') as typeof import('./layout.grid/'),
  'template.maxSpanningForest': require('./template.maxSpanningForest/') as typeof import('./template.maxSpanningForest/'),
  'template.tableSankey': require('./template.tableSankey/') as typeof import('./template.tableSankey/'),
  'tool.d3.mapper': require('./tool.d3.mapper/') as typeof import('./tool.d3.mapper/'),
  'tool.fisheye': require('./tool.fisheye/') as typeof import('./tool.fisheye/'),
  'tool.freezeSize': require('./tool.freezeSize/') as typeof import('./tool.freezeSize/'),
  'tool.gird': require('./tool.grid/') as typeof import('./tool.grid/'),
  'tool.highlightSubgraph': require('./tool.highlightSubgraph/') as typeof import('./tool.highlightSubgraph/'),
  'tool.mapper': require('./tool.mapper/') as typeof import('./tool.mapper/'),
  'tool.minimap': require('./tool.minimap/') as typeof import('./tool.minimap/'),
  'tool.textDisplay': require('./tool.textDisplay/') as typeof import('./tool.textDisplay/'),
  'tool.tooltip': require('./tool.tooltip/') as typeof import('./tool.tooltip/'),
  'util.backbone': require('./util.backbone/') as typeof import('./util.backbone/'),
  'util.dataCleaner': require('./util.dataCleaner/') as typeof import('./util.dataCleaner/'),
  'util.extractSubgraph': require('./util.extractSubgraph/') as typeof import('./util.extractSubgraph/'),
  'util.randomData': require('./util.randomData/') as typeof import('./util.randomData/')
};
